server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://amit:Password#123@ds155714.mlab.com:55714/topic-db

kafka:
  bootstrap:
    address: kafka-2709f680-amit-bb97.aivencloud.com:26578
  topic: topics
