server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/topic-db
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

kafka:
  bootstrap:
    address: localhost:9092
  topic: topics
